### ISSUE TITLE
Add motorbike

### ISSUE THREAD

**Issue by MartinDelille** [NotMyFaultEarth/nmf-app#103]
I use a Yamaha YBR custom 125cc motorbike which doesn't consume so much oil since I fill my ten liter tank every two or three weeks despite I ride it everyday (I mean I used to ride it everyday before the confinement! 😅).

Is it possible to enter more into detail when defining a transport?

**Comment by PierreBresson** [comment]
For the moment we only give an estimation, so we won't go into detail (125 cc or bigger) but we can definitely add motorbike to the list of transport emission :)

**Comment by PierreBresson** [comment]
Done in https://github.com/NotMyFaultEarth/nmf-app/compare/023c5b11b30f...330b071f0f48
