### ISSUE TITLE
Show app version in parameters

### ISSUE THREAD

**Issue by PierreBresson** [NotMyFaultEarth/nmf-app#87]
Would be useful for debugging to show the app version in parameters

**Comment by lucienbl** [comment]
Hello,

I can start with that one 🙂

**Comment by PierreBresson** [comment]
Indeed :)

Here is the design : 

![Group](https://user-images.githubusercontent.com/8709134/77317663-e4dd5600-6d0b-11ea-95c8-d5cdb9e26701.png)

**Comment by theolampert** [comment]
@lucienbl @PierreBresson good to close this one?

**Comment by lucienbl** [comment]
Sure 🙂
